[package]
name = "giphy-alfredworkflow"
version = "4.0.0"
authors = ["Alpha Chen <alpha.chen@gmail.com>"]
edition = "2018"

[dependencies]
alphred = "0.1"
error-chain = "0.11"
rayon = "0.8"
reqwest = "0.7"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
url = "1.5"
url_serde = "0.2"
