[package]
name = "giphy-alfredworkflow"
version = "4.0.4"
authors = ["Alpha Chen <alpha@kejadlen.dev>"]
edition = "2021"

[dependencies]
alphred = "0.1"
anyhow = "1.0"
rayon = "1.6"
reqwest = { version = "0.11", features = ["blocking", "json"] }
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
url = { version = "2.4", features = ["serde"] }
