name: Release

on:
  push:
    tags:
      - v*

jobs:
  release:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Build release
        run: cargo build --release --verbose

      - name: Package release
        run: |
          cp target/release/giphy-alfredworkflow workflow
          zip -rqj giphy.alfredworkflow workflow/*

      - name: Create release
        id: create-release
        uses: actions/create-release@0cb9c9b65d5d1901c1f53e5e66eaf4afd303e70e # latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: |
            # ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload workflow
        uses: actions/upload-release-asset@e8f9f06c4b078e705bd2ea027f0926603fc9b4d5 # v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: ./giphy.alfredworkflow
          asset_name: giphy.alfredworkflow
          asset_content_type: application/zip
